// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package anonymous.proxies;

public class Multiply
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject multiplyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Anonymous.Multiply";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Num1("Num1"),
		Num2("Num2");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Multiply(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Multiply(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject multiplyMendixObject)
	{
		if (multiplyMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, multiplyMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.multiplyMendixObject = multiplyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Multiply.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static anonymous.proxies.Multiply initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return anonymous.proxies.Multiply.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static anonymous.proxies.Multiply initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new anonymous.proxies.Multiply(context, mendixObject);
	}

	public static anonymous.proxies.Multiply load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return anonymous.proxies.Multiply.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Num1
	 */
	public final java.lang.Integer getNum1()
	{
		return getNum1(getContext());
	}

	/**
	 * @param context
	 * @return value of Num1
	 */
	public final java.lang.Integer getNum1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Num1.toString());
	}

	/**
	 * Set value of Num1
	 * @param num1
	 */
	public final void setNum1(java.lang.Integer num1)
	{
		setNum1(getContext(), num1);
	}

	/**
	 * Set value of Num1
	 * @param context
	 * @param num1
	 */
	public final void setNum1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer num1)
	{
		getMendixObject().setValue(context, MemberNames.Num1.toString(), num1);
	}

	/**
	 * @return value of Num2
	 */
	public final java.lang.Integer getNum2()
	{
		return getNum2(getContext());
	}

	/**
	 * @param context
	 * @return value of Num2
	 */
	public final java.lang.Integer getNum2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Num2.toString());
	}

	/**
	 * Set value of Num2
	 * @param num2
	 */
	public final void setNum2(java.lang.Integer num2)
	{
		setNum2(getContext(), num2);
	}

	/**
	 * Set value of Num2
	 * @param context
	 * @param num2
	 */
	public final void setNum2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer num2)
	{
		getMendixObject().setValue(context, MemberNames.Num2.toString(), num2);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return multiplyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final anonymous.proxies.Multiply that = (anonymous.proxies.Multiply) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
