define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../../ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js":
/*!*****************************************************************************************************!*\
  !*** ../../../../../../ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js ***!
  \*****************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "HideProgress": () => (/* binding */ HideProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Hides default progress bar
 * @param {Big} identifier - Identifier of ui which should be hidden. This param is required
 * @returns {Promise.<void>}
 */

async function HideProgress(identifier) {
  // BEGIN USER CODE
  if (identifier == null) {
    return Promise.reject(new Error("Input parameter 'Identifier' is required"));
  }

  mx.ui.hideProgress(Number(identifier));
  return Promise.resolve(); // END USER CODE
}

/***/ }),

/***/ "../../../../../../ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js":
/*!*****************************************************************************************************!*\
  !*** ../../../../../../ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js ***!
  \*****************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "ShowProgress": () => (/* binding */ ShowProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Shows default progress bar
 * @param {string} message - The text to show while loading.
 * @param {boolean} blocking - Block the user interface immediately.
 * @returns {Promise.<Big>}
 */

async function ShowProgress(message, blocking) {
  // BEGIN USER CODE
  const id = mx.ui.showProgress(message, blocking);

  if (id !== undefined) {
    return Promise.resolve(new big_js__WEBPACK_IMPORTED_MODULE_0__.Big(id));
  }

  return Promise.reject(new Error("Could not open the loading dialog")); // END USER CODE
}

/***/ }),

/***/ "../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_GetUserComments.js":
/*!********************************************************************************************************!*\
  !*** ../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_GetUserComments.js ***!
  \********************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_GetUserComments": () => (/* binding */ JS_GetUserComments)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<MxObject[]>}
 */

async function JS_GetUserComments() {
  // BEGIN USER CODE
  const endpoint = 'https://jsonplaceholder.typicode.com/comments';
  const res = await fetch(endpoint);
  const json = await res.json();
  const userComments = json.map(createUserComment);
  return Promise.all(userComments);

  function createUserComment(comment) {
    return new Promise((resolve, reject) => {
      mx.data.create({
        entity: "SalesManager.Comment",
        callback: function (mxObject) {
          mxObject.getAttributes().forEach(function (attributeName) {
            const attributeValue = comment[attributeName];

            if (attributeValue) {
              mxObject.set(attributeName, attributeValue);
            }
          });
          resolve(mxObject);
        },
        error: function (e) {
          reject(new Error("couldnt create a comment entity"));
        }
      });
    });
  } // END USER CODE

}

/***/ }),

/***/ "../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_OpenSharePage.js":
/*!******************************************************************************************************!*\
  !*** ../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_OpenSharePage.js ***!
  \******************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_OpenSharePage": () => (/* binding */ JS_OpenSharePage)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function JS_OpenSharePage() {
  // BEGIN USER CODE
  return new Promise((resolve, reject) => {
    mx.ui.openForm("SalesManager/Share_Web.page.xml", {
      location: "popup",
      callback: function (form) {
        let close = document.getElementsByClassName("close")[0];
        close.remove();
        let share = document.getElementsByClassName("share")[0];
        share.remove();
      }
    });
  }); // END USER CODE
}

/***/ }),

/***/ "../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_SendMailWithMicroflow.js":
/*!**************************************************************************************************************!*\
  !*** ../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_SendMailWithMicroflow.js ***!
  \**************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_SendMailWithMicroflow": () => (/* binding */ JS_SendMailWithMicroflow)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} mail
 * @param {string} name
 * @returns {Promise.<string>}
 */

async function JS_SendMailWithMicroflow(mail, name) {
  // BEGIN USER CODE
  console.warn(mail, name);
  return new Promise((resolve, reject) => {
    mx.data.create({
      entity: "SalesManager.Share",
      callback: function (shareObjectInsideRunTime) {
        shareObjectInsideRunTime.set("Mail", mail);
        shareObjectInsideRunTime.set("Name", name);
        mx.data.action({
          params: {
            applyto: "selection",
            actionname: "SalesManager.ACT_SendSharingMail",
            guids: [shareObjectInsideRunTime.getGuid()]
          },
          callback: function (responseMessage) {
            // expect single MxObject
            console.warn(responseMessage);
            resolve(responseMessage);
          },
          error: function (error) {
            // alert(error.message);
            reject(new Error("Some error occured."));
          }
        });
      },
      error: function (e) {
        reject(new Error("Some error occured."));
      }
    });
  }); // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

"use strict";
module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ }),

/***/ "?391f":
/*!**********************************!*\
  !*** mx-global (ignored module) ***!
  \**********************************/
/***/ (() => {

/* empty */

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
/*!************************************************************************!*\
  !*** ../../../../../../ecommerce-app-main/deployment/tmp/jsactions.js ***!
  \************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "NanoflowCommons$ShowProgress": () => (/* binding */ NanoflowCommons$ShowProgress),
/* harmony export */   "SalesManager$JS_SendMailWithMicroflow": () => (/* binding */ SalesManager$JS_SendMailWithMicroflow),
/* harmony export */   "NanoflowCommons$HideProgress": () => (/* binding */ NanoflowCommons$HideProgress),
/* harmony export */   "SalesManager$JS_GetUserComments": () => (/* binding */ SalesManager$JS_GetUserComments),
/* harmony export */   "SalesManager$JS_OpenSharePage": () => (/* binding */ SalesManager$JS_OpenSharePage)
/* harmony export */ });
const NanoflowCommons$ShowProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress */ "../../../../../../ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js"))).ShowProgress;
const SalesManager$JS_SendMailWithMicroflow = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_SendMailWithMicroflow */ "../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_SendMailWithMicroflow.js"))).JS_SendMailWithMicroflow;
const NanoflowCommons$HideProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress */ "../../../../../../ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js"))).HideProgress;
const SalesManager$JS_GetUserComments = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_GetUserComments */ "../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_GetUserComments.js"))).JS_GetUserComments;
const SalesManager$JS_OpenSharePage = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_OpenSharePage */ "../../../../../../ecommerce-app-main/javascriptsource/salesmanager/actions/JS_OpenSharePage.js"))).JS_OpenSharePage;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlQyxZQUFmLENBQTRCQyxVQUE1QixFQUF3QztBQUM5QztBQUNHLE1BQUlBLFVBQVUsSUFBSSxJQUFsQixFQUF3QjtBQUNwQixXQUFPQyxPQUFPLENBQUNDLE1BQVIsQ0FBZSxJQUFJQyxLQUFKLENBQVUsMENBQVYsQ0FBZixDQUFQO0FBQ0g7O0FBQ0RDLEVBQUFBLEVBQUUsQ0FBQ0MsRUFBSCxDQUFNQyxZQUFOLENBQW1CQyxNQUFNLENBQUNQLFVBQUQsQ0FBekI7QUFDQSxTQUFPQyxPQUFPLENBQUNPLE9BQVIsRUFBUCxDQU4yQyxDQU85QztBQUNBOzs7Ozs7Ozs7Ozs7Ozs7OztBQ3pCRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUNPLGVBQWVDLFlBQWYsQ0FBNEJDLE9BQTVCLEVBQXFDQyxRQUFyQyxFQUErQztBQUNyRDtBQUNHLFFBQU1DLEVBQUUsR0FBR1IsRUFBRSxDQUFDQyxFQUFILENBQU1RLFlBQU4sQ0FBbUJILE9BQW5CLEVBQTRCQyxRQUE1QixDQUFYOztBQUNBLE1BQUlDLEVBQUUsS0FBS0UsU0FBWCxFQUFzQjtBQUNsQixXQUFPYixPQUFPLENBQUNPLE9BQVIsQ0FBZ0IsSUFBSVYsdUNBQUosQ0FBUWMsRUFBUixDQUFoQixDQUFQO0FBQ0g7O0FBQ0QsU0FBT1gsT0FBTyxDQUFDQyxNQUFSLENBQWUsSUFBSUMsS0FBSixDQUFVLG1DQUFWLENBQWYsQ0FBUCxDQU5rRCxDQU9yRDtBQUNBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDMUJEO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Q0FHQTtBQUVBOztBQUVBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlWSxrQkFBZixHQUFvQztBQUMxQztBQUNBLFFBQU1DLFFBQVEsR0FBRywrQ0FBakI7QUFDQSxRQUFNQyxHQUFHLEdBQUcsTUFBTUMsS0FBSyxDQUFDRixRQUFELENBQXZCO0FBQ0EsUUFBTUcsSUFBSSxHQUFHLE1BQU1GLEdBQUcsQ0FBQ0UsSUFBSixFQUFuQjtBQUNBLFFBQU1DLFlBQVksR0FBR0QsSUFBSSxDQUFDRSxHQUFMLENBQVNDLGlCQUFULENBQXJCO0FBRUEsU0FBT3JCLE9BQU8sQ0FBQ3NCLEdBQVIsQ0FBWUgsWUFBWixDQUFQOztBQUVBLFdBQVNFLGlCQUFULENBQTJCRSxPQUEzQixFQUFvQztBQUNuQyxXQUFPLElBQUl2QixPQUFKLENBQVksQ0FBQ08sT0FBRCxFQUFVTixNQUFWLEtBQXFCO0FBQ3ZDRSxNQUFBQSxFQUFFLENBQUNxQixJQUFILENBQVFDLE1BQVIsQ0FBZTtBQUNkQyxRQUFBQSxNQUFNLEVBQUUsc0JBRE07QUFFZEMsUUFBQUEsUUFBUSxFQUFFLFVBQVNDLFFBQVQsRUFBbUI7QUFDNUJBLFVBQUFBLFFBQVEsQ0FBQ0MsYUFBVCxHQUF5QkMsT0FBekIsQ0FBaUMsVUFBVUMsYUFBVixFQUF3QjtBQUN4RCxrQkFBTUMsY0FBYyxHQUFHVCxPQUFPLENBQUNRLGFBQUQsQ0FBOUI7O0FBQ0EsZ0JBQUdDLGNBQUgsRUFBa0I7QUFDakJKLGNBQUFBLFFBQVEsQ0FBQ0ssR0FBVCxDQUFhRixhQUFiLEVBQTRCQyxjQUE1QjtBQUNBO0FBQ0QsV0FMRDtBQU1BekIsVUFBQUEsT0FBTyxDQUFDcUIsUUFBRCxDQUFQO0FBQ0EsU0FWYTtBQVdkTSxRQUFBQSxLQUFLLEVBQUUsVUFBU0MsQ0FBVCxFQUFZO0FBQ2xCbEMsVUFBQUEsTUFBTSxDQUFDLElBQUlDLEtBQUosQ0FBVSxpQ0FBVixDQUFELENBQU47QUFDQTtBQWJhLE9BQWY7QUFlQSxLQWhCTSxDQUFQO0FBaUJBLEdBM0J5QyxDQThCMUM7O0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNoREQ7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUNPLGVBQWVrQyxnQkFBZixHQUFrQztBQUN4QztBQUNBLFNBQU8sSUFBSXBDLE9BQUosQ0FBWSxDQUFDTyxPQUFELEVBQVVOLE1BQVYsS0FBb0I7QUFDdENFLElBQUFBLEVBQUUsQ0FBQ0MsRUFBSCxDQUFNaUMsUUFBTixDQUFlLGlDQUFmLEVBQWtEO0FBQ2pEQyxNQUFBQSxRQUFRLEVBQUUsT0FEdUM7QUFFakRYLE1BQUFBLFFBQVEsRUFBRSxVQUFTWSxJQUFULEVBQWU7QUFDeEIsWUFBSUMsS0FBSyxHQUFHQyxRQUFRLENBQUNDLHNCQUFULENBQWdDLE9BQWhDLEVBQXlDLENBQXpDLENBQVo7QUFDQUYsUUFBQUEsS0FBSyxDQUFDRyxNQUFOO0FBQ0EsWUFBSUMsS0FBSyxHQUFHSCxRQUFRLENBQUNDLHNCQUFULENBQWdDLE9BQWhDLEVBQXlDLENBQXpDLENBQVo7QUFDQUUsUUFBQUEsS0FBSyxDQUFDRCxNQUFOO0FBQ0E7QUFQZ0QsS0FBbEQ7QUFTQSxHQVZNLENBQVAsQ0FGd0MsQ0FheEM7QUFDQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQzlCRDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0NBR0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUNPLGVBQWVFLHdCQUFmLENBQXdDQyxJQUF4QyxFQUE4Q0MsSUFBOUMsRUFBb0Q7QUFDMUQ7QUFDQUMsRUFBQUEsT0FBTyxDQUFDQyxJQUFSLENBQWFILElBQWIsRUFBbUJDLElBQW5CO0FBQ0EsU0FBTyxJQUFJL0MsT0FBSixDQUFhLENBQUNPLE9BQUQsRUFBVU4sTUFBVixLQUFxQjtBQUN4Q0UsSUFBQUEsRUFBRSxDQUFDcUIsSUFBSCxDQUFRQyxNQUFSLENBQWU7QUFDZEMsTUFBQUEsTUFBTSxFQUFFLG9CQURNO0FBRWRDLE1BQUFBLFFBQVEsRUFBRSxVQUFTdUIsd0JBQVQsRUFBbUM7QUFDNUNBLFFBQUFBLHdCQUF3QixDQUFDakIsR0FBekIsQ0FBNkIsTUFBN0IsRUFBcUNhLElBQXJDO0FBQ0FJLFFBQUFBLHdCQUF3QixDQUFDakIsR0FBekIsQ0FBNkIsTUFBN0IsRUFBcUNjLElBQXJDO0FBRUE1QyxRQUFBQSxFQUFFLENBQUNxQixJQUFILENBQVEyQixNQUFSLENBQWU7QUFDZEMsVUFBQUEsTUFBTSxFQUFFO0FBQ1BDLFlBQUFBLE9BQU8sRUFBRSxXQURGO0FBRVBDLFlBQUFBLFVBQVUsRUFBRSxrQ0FGTDtBQUdQQyxZQUFBQSxLQUFLLEVBQUUsQ0FBQ0wsd0JBQXdCLENBQUNNLE9BQXpCLEVBQUQ7QUFIQSxXQURNO0FBTWQ3QixVQUFBQSxRQUFRLEVBQUUsVUFBUzhCLGVBQVQsRUFBMEI7QUFDbkM7QUFDQVQsWUFBQUEsT0FBTyxDQUFDQyxJQUFSLENBQWFRLGVBQWI7QUFDQWxELFlBQUFBLE9BQU8sQ0FBQ2tELGVBQUQsQ0FBUDtBQUNBLFdBVmE7QUFXZHZCLFVBQUFBLEtBQUssRUFBRSxVQUFTQSxLQUFULEVBQWdCO0FBQ3RCO0FBQ0FqQyxZQUFBQSxNQUFNLENBQUMsSUFBSUMsS0FBSixDQUFVLHFCQUFWLENBQUQsQ0FBTjtBQUNBO0FBZGEsU0FBZjtBQWdCQSxPQXRCYTtBQXVCZGdDLE1BQUFBLEtBQUssRUFBRSxVQUFTQyxDQUFULEVBQVk7QUFDbEJsQyxRQUFBQSxNQUFNLENBQUMsSUFBSUMsS0FBSixDQUFVLHFCQUFWLENBQUQsQ0FBTjtBQUNBO0FBekJhLEtBQWY7QUEyQkEsR0E1Qk0sQ0FBUCxDQUgwRCxDQWdDMUQ7QUFDQTs7Ozs7Ozs7Ozs7QUNuREQ7Ozs7Ozs7Ozs7QUNBQTs7Ozs7O1VDQUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTs7VUFFQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTs7Ozs7V0N0QkE7V0FDQTtXQUNBO1dBQ0E7V0FDQTtXQUNBLGlDQUFpQyxXQUFXO1dBQzVDO1dBQ0E7Ozs7O1dDUEE7V0FDQTtXQUNBO1dBQ0E7V0FDQSx5Q0FBeUMsd0NBQXdDO1dBQ2pGO1dBQ0E7V0FDQTs7Ozs7V0NQQTs7Ozs7V0NBQTtXQUNBO1dBQ0E7V0FDQSx1REFBdUQsaUJBQWlCO1dBQ3hFO1dBQ0EsZ0RBQWdELGFBQWE7V0FDN0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNOTyxNQUFNd0QsNEJBQTRCLEdBQUcsWUFBWSxDQUFDLE1BQU0sdVJBQVAsRUFBOEZsRCxZQUEvSTtBQUNBLE1BQU1tRCxxQ0FBcUMsR0FBRyxZQUFZLENBQUMsTUFBTSx5U0FBUCxFQUF1R2Qsd0JBQWpLO0FBQ0EsTUFBTWUsNEJBQTRCLEdBQUcsWUFBWSxDQUFDLE1BQU0sdVJBQVAsRUFBOEY5RCxZQUEvSTtBQUNBLE1BQU0rRCwrQkFBK0IsR0FBRyxZQUFZLENBQUMsTUFBTSw2UkFBUCxFQUFpRy9DLGtCQUFySjtBQUNBLE1BQU1nRCw2QkFBNkIsR0FBRyxZQUFZLENBQUMsTUFBTSx5UkFBUCxFQUErRjFCLGdCQUFqSixDIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL25hbm9mbG93Y29tbW9ucy9hY3Rpb25zL0hpZGVQcm9ncmVzcy5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vZWNvbW1lcmNlLWFwcC1tYWluL2phdmFzY3JpcHRzb3VyY2UvbmFub2Zsb3djb21tb25zL2FjdGlvbnMvU2hvd1Byb2dyZXNzLmpzIiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9lY29tbWVyY2UtYXBwLW1haW4vamF2YXNjcmlwdHNvdXJjZS9zYWxlc21hbmFnZXIvYWN0aW9ucy9KU19HZXRVc2VyQ29tbWVudHMuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL3NhbGVzbWFuYWdlci9hY3Rpb25zL0pTX09wZW5TaGFyZVBhZ2UuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL3NhbGVzbWFuYWdlci9hY3Rpb25zL0pTX1NlbmRNYWlsV2l0aE1pY3JvZmxvdy5qcyIsIndlYnBhY2s6Ly8vZXh0ZXJuYWwgYW1kIFwiYmlnLmpzXCIiLCJ3ZWJwYWNrOi8vL214LWdsb2JhbCIsIndlYnBhY2s6Ly8vd2VicGFjay9ib290c3RyYXAiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9jb21wYXQgZ2V0IGRlZmF1bHQgZXhwb3J0Iiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvZGVmaW5lIHByb3BlcnR5IGdldHRlcnMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9oYXNPd25Qcm9wZXJ0eSBzaG9ydGhhbmQiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9tYWtlIG5hbWVzcGFjZSBvYmplY3QiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL2Vjb21tZXJjZS1hcHAtbWFpbi9kZXBsb3ltZW50L3RtcC9qc2FjdGlvbnMuanMiXSwic291cmNlc0NvbnRlbnQiOlsiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEhpZGVzIGRlZmF1bHQgcHJvZ3Jlc3MgYmFyXHJcbiAqIEBwYXJhbSB7QmlnfSBpZGVudGlmaWVyIC0gSWRlbnRpZmllciBvZiB1aSB3aGljaCBzaG91bGQgYmUgaGlkZGVuLiBUaGlzIHBhcmFtIGlzIHJlcXVpcmVkXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBIaWRlUHJvZ3Jlc3MoaWRlbnRpZmllcikge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG4gICAgaWYgKGlkZW50aWZpZXIgPT0gbnVsbCkge1xyXG4gICAgICAgIHJldHVybiBQcm9taXNlLnJlamVjdChuZXcgRXJyb3IoXCJJbnB1dCBwYXJhbWV0ZXIgJ0lkZW50aWZpZXInIGlzIHJlcXVpcmVkXCIpKTtcclxuICAgIH1cclxuICAgIG14LnVpLmhpZGVQcm9ncmVzcyhOdW1iZXIoaWRlbnRpZmllcikpO1xyXG4gICAgcmV0dXJuIFByb21pc2UucmVzb2x2ZSgpO1xyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogU2hvd3MgZGVmYXVsdCBwcm9ncmVzcyBiYXJcclxuICogQHBhcmFtIHtzdHJpbmd9IG1lc3NhZ2UgLSBUaGUgdGV4dCB0byBzaG93IHdoaWxlIGxvYWRpbmcuXHJcbiAqIEBwYXJhbSB7Ym9vbGVhbn0gYmxvY2tpbmcgLSBCbG9jayB0aGUgdXNlciBpbnRlcmZhY2UgaW1tZWRpYXRlbHkuXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjxCaWc+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIFNob3dQcm9ncmVzcyhtZXNzYWdlLCBibG9ja2luZykge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG4gICAgY29uc3QgaWQgPSBteC51aS5zaG93UHJvZ3Jlc3MobWVzc2FnZSwgYmxvY2tpbmcpO1xyXG4gICAgaWYgKGlkICE9PSB1bmRlZmluZWQpIHtcclxuICAgICAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKG5ldyBCaWcoaWQpKTtcclxuICAgIH1cclxuICAgIHJldHVybiBQcm9taXNlLnJlamVjdChuZXcgRXJyb3IoXCJDb3VsZCBub3Qgb3BlbiB0aGUgbG9hZGluZyBkaWFsb2dcIikpO1xyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgXCJteC1nbG9iYWxcIjtcclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG5cdFxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjxNeE9iamVjdFtdPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19HZXRVc2VyQ29tbWVudHMoKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0Y29uc3QgZW5kcG9pbnQgPSAnaHR0cHM6Ly9qc29ucGxhY2Vob2xkZXIudHlwaWNvZGUuY29tL2NvbW1lbnRzJzsgIFxyXG5cdGNvbnN0IHJlcyA9IGF3YWl0IGZldGNoKGVuZHBvaW50KTtcclxuXHRjb25zdCBqc29uID0gYXdhaXQgcmVzLmpzb24oKTtcclxuXHRjb25zdCB1c2VyQ29tbWVudHMgPSBqc29uLm1hcChjcmVhdGVVc2VyQ29tbWVudClcclxuXHJcblx0cmV0dXJuIFByb21pc2UuYWxsKHVzZXJDb21tZW50cyk7XHJcblxyXG5cdGZ1bmN0aW9uIGNyZWF0ZVVzZXJDb21tZW50KGNvbW1lbnQpIHtcclxuXHRcdHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XHJcblx0XHRcdG14LmRhdGEuY3JlYXRlKHtcclxuXHRcdFx0XHRlbnRpdHk6IFwiU2FsZXNNYW5hZ2VyLkNvbW1lbnRcIixcclxuXHRcdFx0XHRjYWxsYmFjazogZnVuY3Rpb24obXhPYmplY3QpIHtcclxuXHRcdFx0XHRcdG14T2JqZWN0LmdldEF0dHJpYnV0ZXMoKS5mb3JFYWNoKGZ1bmN0aW9uIChhdHRyaWJ1dGVOYW1lKXtcclxuXHRcdFx0XHRcdFx0Y29uc3QgYXR0cmlidXRlVmFsdWUgPSBjb21tZW50W2F0dHJpYnV0ZU5hbWVdO1xyXG5cdFx0XHRcdFx0XHRpZihhdHRyaWJ1dGVWYWx1ZSl7XHJcblx0XHRcdFx0XHRcdFx0bXhPYmplY3Quc2V0KGF0dHJpYnV0ZU5hbWUsIGF0dHJpYnV0ZVZhbHVlKVxyXG5cdFx0XHRcdFx0XHR9XHJcblx0XHRcdFx0XHR9KVxyXG5cdFx0XHRcdFx0cmVzb2x2ZShteE9iamVjdClcclxuXHRcdFx0XHR9LFxyXG5cdFx0XHRcdGVycm9yOiBmdW5jdGlvbihlKSB7XHJcblx0XHRcdFx0XHRyZWplY3QobmV3IEVycm9yKFwiY291bGRudCBjcmVhdGUgYSBjb21tZW50IGVudGl0eVwiKSlcdFx0XHRcdFx0XHJcblx0XHRcdFx0fVxyXG5cdFx0XHR9KTtcclxuXHRcdH0pXHJcblx0fVxyXG5cclxuXHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCBcIm14LWdsb2JhbFwiO1xyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEpTX09wZW5TaGFyZVBhZ2UoKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0cmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+e1xyXG5cdFx0bXgudWkub3BlbkZvcm0oXCJTYWxlc01hbmFnZXIvU2hhcmVfV2ViLnBhZ2UueG1sXCIsIHtcclxuXHRcdFx0bG9jYXRpb246IFwicG9wdXBcIixcclxuXHRcdFx0Y2FsbGJhY2s6IGZ1bmN0aW9uKGZvcm0pIHtcclxuXHRcdFx0XHRsZXQgY2xvc2UgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5Q2xhc3NOYW1lKFwiY2xvc2VcIilbMF07XHJcblx0XHRcdFx0Y2xvc2UucmVtb3ZlKCk7XHJcblx0XHRcdFx0bGV0IHNoYXJlID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZShcInNoYXJlXCIpWzBdO1xyXG5cdFx0XHRcdHNoYXJlLnJlbW92ZSgpO1xyXG5cdFx0XHR9XHJcblx0XHR9KTtcclxuXHR9KVxyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgXCJteC1nbG9iYWxcIjtcclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSBtYWlsXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSBuYW1lXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjxzdHJpbmc+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEpTX1NlbmRNYWlsV2l0aE1pY3JvZmxvdyhtYWlsLCBuYW1lKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0Y29uc29sZS53YXJuKG1haWwsIG5hbWUpO1xyXG5cdHJldHVybiBuZXcgUHJvbWlzZSAoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xyXG5cdFx0bXguZGF0YS5jcmVhdGUoe1xyXG5cdFx0XHRlbnRpdHk6IFwiU2FsZXNNYW5hZ2VyLlNoYXJlXCIsXHJcblx0XHRcdGNhbGxiYWNrOiBmdW5jdGlvbihzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUpIHtcclxuXHRcdFx0XHRzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUuc2V0KFwiTWFpbFwiLCBtYWlsKTtcclxuXHRcdFx0XHRzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUuc2V0KFwiTmFtZVwiLCBuYW1lKTtcclxuXHJcblx0XHRcdFx0bXguZGF0YS5hY3Rpb24oe1xyXG5cdFx0XHRcdFx0cGFyYW1zOiB7XHJcblx0XHRcdFx0XHRcdGFwcGx5dG86IFwic2VsZWN0aW9uXCIsXHJcblx0XHRcdFx0XHRcdGFjdGlvbm5hbWU6IFwiU2FsZXNNYW5hZ2VyLkFDVF9TZW5kU2hhcmluZ01haWxcIixcclxuXHRcdFx0XHRcdFx0Z3VpZHM6IFtzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUuZ2V0R3VpZCgpXVxyXG5cdFx0XHRcdFx0fSxcclxuXHRcdFx0XHRcdGNhbGxiYWNrOiBmdW5jdGlvbihyZXNwb25zZU1lc3NhZ2UpIHtcclxuXHRcdFx0XHRcdFx0Ly8gZXhwZWN0IHNpbmdsZSBNeE9iamVjdFxyXG5cdFx0XHRcdFx0XHRjb25zb2xlLndhcm4ocmVzcG9uc2VNZXNzYWdlKVxyXG5cdFx0XHRcdFx0XHRyZXNvbHZlKHJlc3BvbnNlTWVzc2FnZSk7XHJcblx0XHRcdFx0XHR9LFxyXG5cdFx0XHRcdFx0ZXJyb3I6IGZ1bmN0aW9uKGVycm9yKSB7XHJcblx0XHRcdFx0XHRcdC8vIGFsZXJ0KGVycm9yLm1lc3NhZ2UpO1xyXG5cdFx0XHRcdFx0XHRyZWplY3QobmV3IEVycm9yKFwiU29tZSBlcnJvciBvY2N1cmVkLlwiKSlcclxuXHRcdFx0XHRcdH1cclxuXHRcdFx0XHR9KTtcclxuXHRcdFx0fSxcclxuXHRcdFx0ZXJyb3I6IGZ1bmN0aW9uKGUpIHtcclxuXHRcdFx0XHRyZWplY3QobmV3IEVycm9yKFwiU29tZSBlcnJvciBvY2N1cmVkLlwiKSlcclxuXHRcdFx0fVxyXG5cdFx0fSk7XHJcblx0fSlcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwibW9kdWxlLmV4cG9ydHMgPSBfX1dFQlBBQ0tfRVhURVJOQUxfTU9EVUxFX2JpZ19qc19fOyIsIi8qIGVtcHR5ICovIiwiLy8gVGhlIG1vZHVsZSBjYWNoZVxudmFyIF9fd2VicGFja19tb2R1bGVfY2FjaGVfXyA9IHt9O1xuXG4vLyBUaGUgcmVxdWlyZSBmdW5jdGlvblxuZnVuY3Rpb24gX193ZWJwYWNrX3JlcXVpcmVfXyhtb2R1bGVJZCkge1xuXHQvLyBDaGVjayBpZiBtb2R1bGUgaXMgaW4gY2FjaGVcblx0dmFyIGNhY2hlZE1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF07XG5cdGlmIChjYWNoZWRNb2R1bGUgIT09IHVuZGVmaW5lZCkge1xuXHRcdHJldHVybiBjYWNoZWRNb2R1bGUuZXhwb3J0cztcblx0fVxuXHQvLyBDcmVhdGUgYSBuZXcgbW9kdWxlIChhbmQgcHV0IGl0IGludG8gdGhlIGNhY2hlKVxuXHR2YXIgbW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXSA9IHtcblx0XHQvLyBubyBtb2R1bGUuaWQgbmVlZGVkXG5cdFx0Ly8gbm8gbW9kdWxlLmxvYWRlZCBuZWVkZWRcblx0XHRleHBvcnRzOiB7fVxuXHR9O1xuXG5cdC8vIEV4ZWN1dGUgdGhlIG1vZHVsZSBmdW5jdGlvblxuXHRfX3dlYnBhY2tfbW9kdWxlc19fW21vZHVsZUlkXShtb2R1bGUsIG1vZHVsZS5leHBvcnRzLCBfX3dlYnBhY2tfcmVxdWlyZV9fKTtcblxuXHQvLyBSZXR1cm4gdGhlIGV4cG9ydHMgb2YgdGhlIG1vZHVsZVxuXHRyZXR1cm4gbW9kdWxlLmV4cG9ydHM7XG59XG5cbiIsIi8vIGdldERlZmF1bHRFeHBvcnQgZnVuY3Rpb24gZm9yIGNvbXBhdGliaWxpdHkgd2l0aCBub24taGFybW9ueSBtb2R1bGVzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLm4gPSAobW9kdWxlKSA9PiB7XG5cdHZhciBnZXR0ZXIgPSBtb2R1bGUgJiYgbW9kdWxlLl9fZXNNb2R1bGUgP1xuXHRcdCgpID0+IChtb2R1bGVbJ2RlZmF1bHQnXSkgOlxuXHRcdCgpID0+IChtb2R1bGUpO1xuXHRfX3dlYnBhY2tfcmVxdWlyZV9fLmQoZ2V0dGVyLCB7IGE6IGdldHRlciB9KTtcblx0cmV0dXJuIGdldHRlcjtcbn07IiwiLy8gZGVmaW5lIGdldHRlciBmdW5jdGlvbnMgZm9yIGhhcm1vbnkgZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5kID0gKGV4cG9ydHMsIGRlZmluaXRpb24pID0+IHtcblx0Zm9yKHZhciBrZXkgaW4gZGVmaW5pdGlvbikge1xuXHRcdGlmKF9fd2VicGFja19yZXF1aXJlX18ubyhkZWZpbml0aW9uLCBrZXkpICYmICFfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZXhwb3J0cywga2V5KSkge1xuXHRcdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIGtleSwgeyBlbnVtZXJhYmxlOiB0cnVlLCBnZXQ6IGRlZmluaXRpb25ba2V5XSB9KTtcblx0XHR9XG5cdH1cbn07IiwiX193ZWJwYWNrX3JlcXVpcmVfXy5vID0gKG9iaiwgcHJvcCkgPT4gKE9iamVjdC5wcm90b3R5cGUuaGFzT3duUHJvcGVydHkuY2FsbChvYmosIHByb3ApKSIsIi8vIGRlZmluZSBfX2VzTW9kdWxlIG9uIGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uciA9IChleHBvcnRzKSA9PiB7XG5cdGlmKHR5cGVvZiBTeW1ib2wgIT09ICd1bmRlZmluZWQnICYmIFN5bWJvbC50b1N0cmluZ1RhZykge1xuXHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBTeW1ib2wudG9TdHJpbmdUYWcsIHsgdmFsdWU6ICdNb2R1bGUnIH0pO1xuXHR9XG5cdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCAnX19lc01vZHVsZScsIHsgdmFsdWU6IHRydWUgfSk7XG59OyIsImV4cG9ydCBjb25zdCBOYW5vZmxvd0NvbW1vbnMkU2hvd1Byb2dyZXNzID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL25hbm9mbG93Y29tbW9ucy9hY3Rpb25zL1Nob3dQcm9ncmVzc1wiKSkuU2hvd1Byb2dyZXNzO1xuZXhwb3J0IGNvbnN0IFNhbGVzTWFuYWdlciRKU19TZW5kTWFpbFdpdGhNaWNyb2Zsb3cgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovZWNvbW1lcmNlLWFwcC1tYWluL2phdmFzY3JpcHRzb3VyY2Uvc2FsZXNtYW5hZ2VyL2FjdGlvbnMvSlNfU2VuZE1haWxXaXRoTWljcm9mbG93XCIpKS5KU19TZW5kTWFpbFdpdGhNaWNyb2Zsb3c7XG5leHBvcnQgY29uc3QgTmFub2Zsb3dDb21tb25zJEhpZGVQcm9ncmVzcyA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJDOi9lY29tbWVyY2UtYXBwLW1haW4vamF2YXNjcmlwdHNvdXJjZS9uYW5vZmxvd2NvbW1vbnMvYWN0aW9ucy9IaWRlUHJvZ3Jlc3NcIikpLkhpZGVQcm9ncmVzcztcbmV4cG9ydCBjb25zdCBTYWxlc01hbmFnZXIkSlNfR2V0VXNlckNvbW1lbnRzID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL3NhbGVzbWFuYWdlci9hY3Rpb25zL0pTX0dldFVzZXJDb21tZW50c1wiKSkuSlNfR2V0VXNlckNvbW1lbnRzO1xuZXhwb3J0IGNvbnN0IFNhbGVzTWFuYWdlciRKU19PcGVuU2hhcmVQYWdlID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL3NhbGVzbWFuYWdlci9hY3Rpb25zL0pTX09wZW5TaGFyZVBhZ2VcIikpLkpTX09wZW5TaGFyZVBhZ2U7XG4iXSwibmFtZXMiOlsiQmlnIiwiSGlkZVByb2dyZXNzIiwiaWRlbnRpZmllciIsIlByb21pc2UiLCJyZWplY3QiLCJFcnJvciIsIm14IiwidWkiLCJoaWRlUHJvZ3Jlc3MiLCJOdW1iZXIiLCJyZXNvbHZlIiwiU2hvd1Byb2dyZXNzIiwibWVzc2FnZSIsImJsb2NraW5nIiwiaWQiLCJzaG93UHJvZ3Jlc3MiLCJ1bmRlZmluZWQiLCJKU19HZXRVc2VyQ29tbWVudHMiLCJlbmRwb2ludCIsInJlcyIsImZldGNoIiwianNvbiIsInVzZXJDb21tZW50cyIsIm1hcCIsImNyZWF0ZVVzZXJDb21tZW50IiwiYWxsIiwiY29tbWVudCIsImRhdGEiLCJjcmVhdGUiLCJlbnRpdHkiLCJjYWxsYmFjayIsIm14T2JqZWN0IiwiZ2V0QXR0cmlidXRlcyIsImZvckVhY2giLCJhdHRyaWJ1dGVOYW1lIiwiYXR0cmlidXRlVmFsdWUiLCJzZXQiLCJlcnJvciIsImUiLCJKU19PcGVuU2hhcmVQYWdlIiwib3BlbkZvcm0iLCJsb2NhdGlvbiIsImZvcm0iLCJjbG9zZSIsImRvY3VtZW50IiwiZ2V0RWxlbWVudHNCeUNsYXNzTmFtZSIsInJlbW92ZSIsInNoYXJlIiwiSlNfU2VuZE1haWxXaXRoTWljcm9mbG93IiwibWFpbCIsIm5hbWUiLCJjb25zb2xlIiwid2FybiIsInNoYXJlT2JqZWN0SW5zaWRlUnVuVGltZSIsImFjdGlvbiIsInBhcmFtcyIsImFwcGx5dG8iLCJhY3Rpb25uYW1lIiwiZ3VpZHMiLCJnZXRHdWlkIiwicmVzcG9uc2VNZXNzYWdlIiwiTmFub2Zsb3dDb21tb25zJFNob3dQcm9ncmVzcyIsIlNhbGVzTWFuYWdlciRKU19TZW5kTWFpbFdpdGhNaWNyb2Zsb3ciLCJOYW5vZmxvd0NvbW1vbnMkSGlkZVByb2dyZXNzIiwiU2FsZXNNYW5hZ2VyJEpTX0dldFVzZXJDb21tZW50cyIsIlNhbGVzTWFuYWdlciRKU19PcGVuU2hhcmVQYWdlIl0sInNvdXJjZVJvb3QiOiIifQ==