// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package admin.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Admin module
	public static void aCT_ShowMyAccount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Admin.ACT_ShowMyAccount").withParams(params).execute(context);
	}
	public static void aCT_Upload(IContext context, administration.proxies.ProfileImage _profileImage, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ProfileImage", _profileImage == null ? null : _profileImage.getMendixObject());
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("Admin.ACT_Upload").withParams(params).execute(context);
	}
	public static void aCT_UserProfile(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("Admin.ACT_UserProfile").withParams(params).execute(context);
	}
	public static administration.proxies.Account dS_CurrentUser(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Admin.DS_CurrentUser").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
}
